/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b8c8dd",
        "error": "#ffb4ab",
        "inverse-primary": "#506600",
        "surface-container-low": "#0e1c2d",
        "on-background": "#d5e4fa",
        "on-secondary": "#223242",
        "secondary-fixed-dim": "#b8c8dd",
        "surface-dim": "#051424",
        "surface-container-lowest": "#010f1f",
        "primary-fixed": "#c3f400",
        "on-tertiary": "#233242",
        "background": "#051424",
        "on-surface-muted": "#8e9379",
        "tertiary": "#ffffff",
        "surface-bright": "#2c3a4c",
        "on-primary-fixed-variant": "#3c4d00",
        "primary-fixed-dim": "#abd600",
        "glow-primary": "rgba(195, 244, 0, 0.15)",
        "on-secondary-container": "#a7b7cb",
        "on-tertiary-fixed": "#0d1d2d",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#39485a",
        "inverse-on-surface": "#233143",
        "secondary": "#b8c8dd",
        "tertiary-container": "#d4e4fa",
        "outline-variant": "#444933",
        "active-safe": "#abd600",
        "surface-container-high": "#1d2b3c",
        "surface-container": "#122031",
        "on-tertiary-fixed-variant": "#39485a",
        "on-secondary-fixed": "#0d1d2c",
        "surface-gradient-start": "rgba(28, 43, 60, 0.4)",
        "surface-tint": "#abd600",
        "on-surface-variant": "#c4c9ad",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "surface-glass": "rgba(5, 20, 36, 0.6)",
        "on-surface": "#d5e4fa",
        "on-primary": "#283500",
        "primary-container": "#c3f400",
        "surface-container-highest": "#283647",
        "inverse-surface": "#d5e4fa",
        "secondary-container": "#39485a",
        "tertiary-fixed": "#d4e4fa",
        "on-tertiary-container": "#576678",
        "on-primary-fixed": "#161f00",
        "outline": "#8e9379",
        "secondary-fixed": "#d4e4fa",
        "surface": "#051424",
        "primary": "#ffffff",
        "on-primary-container": "#556d00",
        "surface-variant": "#283647"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "xl": "40px",
        "container-margin": "20px",
        "md": "16px",
        "gutter": "12px",
        "sm": "8px",
        "unit": "4px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-sm": ["Geist"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "mono-data": ["Geist"],
        "body-md": ["Inter"]
      }
    },
  },
  plugins: [],
}
